name: Deploy to Coolify

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify Webhook
        run: |
          if [ -z "${{ secrets.COOLIFY_WEBHOOK_URL }}" ]; then
            echo "Erro: O segredo COOLIFY_WEBHOOK_URL não está configurado."
            exit 1
          fi
          
          curl --fail --request GET "${{ secrets.COOLIFY_WEBHOOK_URL }}" \
               --header "Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN }}"
